import type { Idl } from '@coral-xyz/anchor'

export interface LocalnetConfig {
  rpcUrl: string
  programId: string
  stakingMint: string
  rewardMint: string
  poolState: string
  stakingVault: string
  userStakingAccount: string
  userRewardAccount: string
  walletSecretKey: number[]
}

// `localnet.json` and `idl/solana_yield_vibe.json` are generated by
// `scripts/setup_local_env.ts` (the former is gitignored). import.meta.glob
// tolerates a missing file (returns {}), so the app renders a helpful
// "run setup" message instead of failing the build.
const configModules = import.meta.glob('./localnet.json', { eager: true }) as Record<
  string,
  { default: LocalnetConfig }
>
export const localnet: LocalnetConfig | null = Object.values(configModules)[0]?.default ?? null

const idlModules = import.meta.glob('./idl/solana_yield_vibe.json', { eager: true }) as Record<
  string,
  { default: Idl }
>
export const idl: Idl | null = Object.values(idlModules)[0]?.default ?? null
